[server]
# Use the Python interpreter from the uv virtual environment
pythonPath = "../.venv/bin/python"

[theme]
primaryColor = "#80CC39"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730" 